getPic ({"pvcontainer1":[
"03.Taxa/3.stack/Domain.bar.png",
"03.Taxa/3.stack/Phylum.bar.png",
"03.Taxa/3.stack/Class.bar.png",
"03.Taxa/3.stack/Order.bar.png",
"03.Taxa/3.stack/Family.bar.png",
"03.Taxa/3.stack/Genus.bar.png",
"03.Taxa/3.stack/Species.bar.png"
],
"pvcontainer2":[
"03.Taxa/4.heatmap/Phylum.heatmap.png",
"03.Taxa/4.heatmap/Class.heatmap.png",
"03.Taxa/4.heatmap/Order.heatmap.png",
"03.Taxa/4.heatmap/Family.heatmap.png",
"03.Taxa/4.heatmap/Genus.heatmap.png",
"03.Taxa/4.heatmap/Species.heatmap.png"
],
"pvcontainer3":[
"03.Taxa/6.correlation/Phylum/Phylum.pearson.network.nolab.png",
"03.Taxa/6.correlation/Class/Class.pearson.network.nolab.png",
"03.Taxa/6.correlation/Order/Order.pearson.network.nolab.png",
"03.Taxa/6.correlation/Family/Family.pearson.network.nolab.png",
"03.Taxa/6.correlation/Genus/Genus.pearson.network.nolab.png",
"03.Taxa/6.correlation/Species/Species.pearson.network.nolab.png"
],
"container4":{
    "tb0":["04.Taxa_diff/7.venn/Genus/A_vs_B/venn.png",
"",
"04.Taxa_diff/7.venn/Genus/A_vs_B/upset.png",
""],
"tb1":["04.Taxa_diff/7.venn/Genus/B_vs_C/venn.png",
"",
"04.Taxa_diff/7.venn/Genus/B_vs_C/upset.png",
""],
"tb2":["04.Taxa_diff/7.venn/Genus/A_vs_B_vs_C/venn.png",
"",
"04.Taxa_diff/7.venn/Genus/A_vs_B_vs_C/upset.png",
""]
},
"pvcontainer5":[
"04.Taxa_diff/1.multi-test/Genus/A_vs_B.t-test.extended_error_bar.png",
"04.Taxa_diff/1.multi-test/Genus/B_vs_C.t-test.extended_error_bar.png"
],
"container6":{
    "tb0":["04.Taxa_diff/2.lefse/A-vs-B.Lefse.png",
"",
"04.Taxa_diff/2.lefse/A-vs-B.Lefse.cladogram.png",
""],
"tb1":["04.Taxa_diff/2.lefse/B-vs-C.Lefse.png",
"",
"04.Taxa_diff/2.lefse/B-vs-C.Lefse.cladogram.png",
""],
"tb2":["04.Taxa_diff/2.lefse/A-vs-B-vs-C.Lefse.png",
"",
"04.Taxa_diff/2.lefse/A-vs-B-vs-C.Lefse.cladogram.png",
""]
},
"pvcontainer7":[
"04.Taxa_diff/4.randomForest/Genus/A_vs_B.randomForest.varImp.png",
"04.Taxa_diff/4.randomForest/Genus/B_vs_C.randomForest.varImp.png"
],
"pvcontainer8":[
"04.Taxa_diff/5.roc/Genus/A_vs_B.all.roc.png",
"04.Taxa_diff/5.roc/Genus/B_vs_C.all.roc.png"
],
"pvcontainer9":[
"04.Taxa_diff/3.ternary/Genus.A_vs_B_vs_C.Ternary_plot.png"
],
"pvcontainer10":[
"04.Taxa_diff/6.indicator/Genus/A_vs_B.indval.png",
"04.Taxa_diff/6.indicator/Genus/B_vs_C.indval.png",
"04.Taxa_diff/6.indicator/Genus/A_vs_B_vs_C.indval.png"
],
"pvcontainer11":[
"05.Alpha_diversity/2.rarefactions_plot/sobs.samples.png",
"05.Alpha_diversity/2.rarefactions_plot/shannon.samples.png",
"05.Alpha_diversity/2.rarefactions_plot/simpson.samples.png",
"05.Alpha_diversity/2.rarefactions_plot/chao.samples.png",
"05.Alpha_diversity/2.rarefactions_plot/ace.samples.png",
"05.Alpha_diversity/2.rarefactions_plot/goods_coverage.samples.png",
"05.Alpha_diversity/2.rarefactions_plot/pd.samples.png"
],
"pvcontainer12":[
"05.Alpha_diversity/4.diff_alpha_diversity/sobs/A-vs-B-vs-C.cld.png"
],
"pvcontainer13":[
"06.Beta_diversity/1.Dissimilarity_indices/OTU/unweighted_unifrac.heatmap.png",
"06.Beta_diversity/1.Dissimilarity_indices/OTU/weighted_unifrac.heatmap.png",
"06.Beta_diversity/1.Dissimilarity_indices/OTU/bray.heatmap.png",
"06.Beta_diversity/1.Dissimilarity_indices/OTU/jaccard.heatmap.png"
],
"pvcontainer14":[
"06.Beta_diversity/1.Dissimilarity_indices/OTU/unweighted_unifrac.Genus.UPGMA_stack.png",
"06.Beta_diversity/1.Dissimilarity_indices/OTU/weighted_unifrac.Genus.UPGMA_stack.png",
"06.Beta_diversity/1.Dissimilarity_indices/OTU/bray.Genus.UPGMA_stack.png",
"06.Beta_diversity/1.Dissimilarity_indices/OTU/jaccard.Genus.UPGMA_stack.png"
],
"pvcontainer15":[
"06.Beta_diversity/2.pcoa/OTU/unweighted_unifrac/PCoA1-2.nonlabs.png",
"06.Beta_diversity/2.pcoa/OTU/weighted_unifrac/PCoA1-2.nonlabs.png",
"06.Beta_diversity/2.pcoa/OTU/bray/PCoA1-2.nonlabs.png",
"06.Beta_diversity/2.pcoa/OTU/jaccard/PCoA1-2.nonlabs.png"
],
"pvcontainer16":[
"06.Beta_diversity/3.nmds/OTU/unweighted_unifrac/NMDS1-2.nonlabs.png",
"06.Beta_diversity/3.nmds/OTU/weighted_unifrac/NMDS1-2.nonlabs.png",
"06.Beta_diversity/3.nmds/OTU/bray/NMDS1-2.nonlabs.png",
"06.Beta_diversity/3.nmds/OTU/jaccard/NMDS1-2.nonlabs.png"
],
"pvcontainer17":[
"06.Beta_diversity/4.anosim_and_adonis/OTU/unweighted_unifrac/A-vs-B.anosim.box.png",
"06.Beta_diversity/4.anosim_and_adonis/OTU/unweighted_unifrac/B-vs-C.anosim.box.png",
"06.Beta_diversity/4.anosim_and_adonis/OTU/unweighted_unifrac/A-vs-B-vs-C.anosim.box.png"
],
"pvcontainer18":[
"07.Function/BugBase/otu_contributions/Aerobic.png",
"07.Function/BugBase/otu_contributions/Anaerobic.png",
"07.Function/BugBase/otu_contributions/Contains_Mobile_Elements.png",
"07.Function/BugBase/otu_contributions/Facultatively_Anaerobic.png",
"07.Function/BugBase/otu_contributions/Forms_Biofilms.png",
"07.Function/BugBase/otu_contributions/Gram_Negative.png",
"07.Function/BugBase/otu_contributions/Gram_Positive.png",
"07.Function/BugBase/otu_contributions/Potentially_Pathogenic.png",
"07.Function/BugBase/otu_contributions/Stress_Tolerant.png"
],
"pvcontainer19":[
"07.Function/BugBase/predicted_phenotypes/Aerobic.png",
"07.Function/BugBase/predicted_phenotypes/Anaerobic.png",
"07.Function/BugBase/predicted_phenotypes/Contains_Mobile_Elements.png",
"07.Function/BugBase/predicted_phenotypes/Facultatively_Anaerobic.png",
"07.Function/BugBase/predicted_phenotypes/Forms_Biofilms.png",
"07.Function/BugBase/predicted_phenotypes/Gram_Negative.png",
"07.Function/BugBase/predicted_phenotypes/Gram_Positive.png",
"07.Function/BugBase/predicted_phenotypes/Potentially_Pathogenic.png",
"07.Function/BugBase/predicted_phenotypes/Stress_Tolerant.png"
],
})